#Numpy Arrays Over Lists
1. Single data type, faster to read data.
2. Size of data is small, therefore easy to read.
3. Store data in contiguous form.

In [2]:
import numpy as np

#Basics


In [12]:
a = np.array([1,2,3], dtype='int8')
a

array([1, 2, 3], dtype=int8)

In [14]:
b = np.array([[[1,2,3],[3,2,1]],[[4,3,2],[1,2,1]]],dtype='int8')
b

array([[[1, 2, 3],
        [3, 2, 1]],

       [[4, 3, 2],
        [1, 2, 1]]], dtype=int8)

In [7]:
a.ndim,b.ndim

(1, 3)

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 2, 3)

In [15]:
a.dtype,b.dtype

(dtype('int8'), dtype('int8'))

In [16]:
a.size,a.shape

(3, (3,))

In [17]:
b.size

12

Accessing elements

In [19]:
ar1 = np.array([1,2,3,4,5,6,7,8])
ar1[2:-1]

array([3, 4, 5, 6, 7])

In [20]:
ar2 = np.array([[2,1,3,4,5,6,7],[9,8,3,4,6,1,3]])
ar2

array([[2, 1, 3, 4, 5, 6, 7],
       [9, 8, 3, 4, 6, 1, 3]])

In [21]:
ar2[1,5]

np.int64(1)

In [22]:
ar2[0,2:5]

array([3, 4, 5])

In [24]:
ar2[:,5] = [2,3]

In [25]:
ar2

array([[2, 1, 3, 4, 5, 2, 7],
       [9, 8, 3, 4, 6, 3, 3]])

In [27]:
ar3 = np.array([[[2,1],[3,4],[5,4],[2,2]],[[11,1],[3,2],[5,30],[6,5]],[[6,7],[2,4],[7,8],[9,10]]])
ar3

array([[[ 2,  1],
        [ 3,  4],
        [ 5,  4],
        [ 2,  2]],

       [[11,  1],
        [ 3,  2],
        [ 5, 30],
        [ 6,  5]],

       [[ 6,  7],
        [ 2,  4],
        [ 7,  8],
        [ 9, 10]]])

In [30]:
ar3[1,:,:]

array([[11,  1],
       [ 3,  2],
       [ 5, 30],
       [ 6,  5]])

Initializing different types of arrays

In [31]:
np.zeros((3,4,2,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [32]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.full((2,3,4),9)

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [36]:
ran = np.random.random((2,3))
ran

array([[0.37238529, 0.02479744, 0.87962177],
       [0.65435667, 0.75248023, 0.36512646]])

In [39]:
rann = np.random.randint(2,10,(4,5))
rann

array([[2, 7, 7, 2, 2],
       [7, 8, 3, 8, 5],
       [2, 5, 3, 7, 7],
       [8, 6, 7, 2, 3]])

In [40]:
eg = np.ones((5,5))
eg[1:5,1:5] = 0
eg[2,2] = 9
eg

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 9., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

Copying arrays

In [41]:
a = np.array([2,11,3,2])
b = a.copy()
b

array([ 2, 11,  3,  2])

#Mathematics

In [42]:
a*6

array([12, 66, 18, 12])

In [45]:
a*6/b

array([6., 6., 6., 6.])

In [44]:
b

array([ 2, 11,  3,  2])

Linear Algebra

In [49]:
a1 = np.array([[1,2,3,5],[4,3,5,1]])
a2 = np.full((4,5),2)
print(a1)
print("  ")
print(a2)

[[1 2 3 5]
 [4 3 5 1]]
  
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [52]:
np.matmul(a1,a2)

array([[22, 22, 22, 22, 22],
       [26, 26, 26, 26, 26]])

In [53]:
a3 = np.identity(4)

In [55]:
np.linalg.det(a3)

np.float64(1.0)

Statistics

In [57]:
a1 = np.random.randint(2,11,(4,5))
a1

array([[ 4,  6,  5,  4,  2],
       [ 2,  4, 10,  3,  8],
       [ 8,  4,  6, 10,  7],
       [ 8,  2,  5, 10,  5]])

In [61]:
np.min(a1[:,2])

np.int64(5)

In [62]:
np.sum(a1)

np.int64(113)

In [64]:
np.sum(a1[1:3,1:4])

np.int64(37)

Reorganizing Array

In [67]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
np.reshape(a,(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [69]:
b = np.array([21,11,33,11])
c = np.array([4,5,6,8])

In [71]:
np.vstack([b,c,b,c])

array([[21, 11, 33, 11],
       [ 4,  5,  6,  8],
       [21, 11, 33, 11],
       [ 4,  5,  6,  8]])

In [72]:
np.hstack([b,c])

array([21, 11, 33, 11,  4,  5,  6,  8])

Load Data From a File


In [74]:
b = b.astype('int8')
b

array([21, 11, 33, 11], dtype=int8)

In [75]:
testData = np.genfromtxt('test.txt',delimiter=',')
testData

array([[1., 2., 3., 4., 5., 6., 7.],
       [2., 1., 3., 4., 2., 5., 6.],
       [6., 5., 4., 2., 3., 1., 6.],
       [7., 5., 3., 8., 2., 3., 5.]])

In [76]:
testData > 4

array([[False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True],
       [ True,  True, False, False, False, False,  True],
       [ True,  True, False,  True, False, False,  True]])

In [78]:
testData[testData > 4]

array([5., 6., 7., 5., 6., 6., 5., 6., 7., 5., 8., 5.])

In [79]:
np.any(testData>4,axis=0)

array([ True,  True, False,  True,  True,  True,  True])

In [80]:
np.all(testData>4,axis=0)

array([False, False, False, False, False, False,  True])